In [1]:
import pandas as pd

In [2]:
# Downloading and unzipping the dataset
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv.

--2026-04-02 14:19:17--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 3.169.117.63, 3.169.117.64, 3.169.117.127, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|3.169.117.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M  66.3MB/s    in 1.0s

2026-04-02 14:19:19 (66.3 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: missing destination file operand after 'zomato_dataset.csv.'
Try 'mv --help' for more information.

In [3]:
df= pd.read_csv("/content/zomato_dataset.csv")

In [4]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [5]:
df.tail(10)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
23183,https://www.zomato.com/bangalore/bar-bar-white...,"Level 2, Phoenix Marketcity, Whitefield, Banga...",BAR BAR,No,Yes,4.1 /5,1003,+91 7338630404\n+91 8067266651,Whitefield,"Bar, Casual Dining","Mocktails, Cocktails, Pizza, Chicken Tikka, Na...","Continental, North Indian, Italian",'1500.0',"[('Rated 4.0', ""RATED\n In an increasingly ov...",[],Pubs and bars,Whitefield
23184,https://www.zomato.com/bangalore/the-beer-cafe...,"Unit 4A - 4B, Upper Ground Floor, VR Bengaluru...",The Beer Cafe,Yes,Yes,4.1 /5,673,+91 8929188573,Whitefield,Pub,"Cocktails, Wheat Beer, Bruschettas, Pasta, Bur...","Finger Food, North Indian, Chinese, Italian",'1400.0',"[('Rated 2.0', ""RATED\n We went out to this p...",[],Pubs and bars,Whitefield
23185,https://www.zomato.com/bangalore/pablos-gastro...,"2, Graphite India Road, Doddanekundi Industria...",Pablo's Gastrobar,No,No,4.0 /5,1094,00 9108214702,Whitefield,Bar,"Cocktails, Beer, Pizza, Long Island Iced Tea, ...","Finger Food, American, Asian, Italian",'1450.0',"[('Rated 4.0', 'RATED\n A good place to dine....",[],Pubs and bars,Whitefield
23186,https://www.zomato.com/bangalore/olivers-pub-d...,"ITPL Ascendas Park Square Mall, ITPL, First Fl...",Oliver's Pub & Diner,Yes,Yes,3.9 /5,548,+91 8043691111\n+91 8028026519,Whitefield,"Pub, Casual Dining","Pizza, Beer, Cocktails, Nachos, Pasta, Moo Bur...","Finger Food, American, Continental, Burger, Pizza",'1500.0',"[('Rated 4.0', ""RATED\n I had :-\n\n1. Italia...",[],Pubs and bars,Whitefield
23187,https://www.zomato.com/bangalore/smaaash-white...,"2nd Floor, Phoenix Market City, Whitefield, Ba...",Smaaash,No,Yes,4.0 /5,189,+91 9900069474\n+91 7899644468,Whitefield,"Casual Dining, Pub","Pizza, Beer","North Indian, Pizza, Chinese",'1500.0',"[('Rated 3.0', 'RATED\n Like this place for z...",[],Pubs and bars,Whitefield
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

In [6]:
df.iloc[100]

url                            https://www.zomato.com/bangalore/chutney-chang...
address                        Cosmopolitan Club, 22nd Cross, 3rd Block, Jaya...
name                                                               Chutney Chang
online_order                                                                 Yes
book_table                                                                   Yes
rate                                                                       4.1/5
votes                                                                       2339
phone                                             080 22443007\r\n+91 9901967373
location                                                               Jayanagar
rest_type                                                          Casual Dining
dish_liked                     Veg Momos, Brownie Chocolate, Palak Chaat, Mut...
cuisines                                              North Indian, Chinese, BBQ
approx_cost(for two people)                                             '1500.0'
reviews_list                   [('Rated 4.0', 'RATED\n  Great place for team ...
menu_item                                                                     []
listed_in(type)                                                         Delivery
listed_in(city)                                                     Banashankari
Name: 100, dtype: object

In [7]:
df.iloc[1:4]

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari

In [8]:
df.iloc[1:9:3]

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
7,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",'700.0',"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari

In [9]:
df_explicit = df.set_index("name")

In [10]:
df_explicit

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

In [11]:
df_explicit.loc["Jalsa"]

,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
name,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\r\r\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Banashankari
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,804,080 42297555\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Paneer Lajawab, Masala Pa...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n Super ambience\nGreat...",[],Dine-out,Basavanagudi
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2/5,2173,+91 7406617555\r\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n A pretty decent place...",[],Delivery,Brookefield
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Delivery,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1 /5,783,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Dine-out,Jayanagar
Jalsa,https://www.zomato.com/bangalore/jalsa-maratha...,"25/7, Doddannakundi, Outer Ring Road, Mahadeva...",Yes,Yes,4.2 /5,2189,+91 7406617555\n+91 7406627555,Marathahalli,Casual Dining,"Mutton Curry, Stuffed Mushroom, Laccha Paratha...","North Indian, Mughlai",'1500.0',"[('Rated 4.0', 'RATED\n Friendly staff, avera...",[],Delivery,Marathahalli

In [14]:
df_explicit.reset_index(inplace=True)

In [15]:
df_explicit

,name,url,address,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield
23191,Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield

In [17]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23193 non-null  object
 14  menu_item                    23193 non-null  object
 15  listed_in(type)              23193 non-null  object
 16  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(16)
memory usage: 3.0+ MB

In [20]:
df.shape

(23193, 17)

In [21]:
hahaha = df.iloc[100]

In [23]:
hahaha.shape

(17,)

In [24]:
data = {
    "Restaurant": ["R1", "R2", "R3"],
    "Votes": [120, 240, 150],
    "Rating": [4.1, 4.5, 3.9]
}

In [25]:
pd.DataFrame(data)

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9

In [26]:
import numpy as np
ratings = np.array([4.1, 4.5, 3.9])

In [31]:
Se = pd.Series(ratings)

In [28]:
de = pd.DataFrame(ratings)

In [32]:
Se.shape

(3,)

In [33]:
de.shape

(3, 1)

In [34]:
df["name"]

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...
23188                                   Izakaya Gastro Pub
23189          M Bar - Bengaluru Marriott Hotel Whitefield
23190                               Keys Cafe - Keys Hotel
23191                                              Bhagini
23192    Chime - Sheraton Grand Bengaluru Whitefield Ho...
Name: name, Length: 23193, dtype: object

In [37]:
df[["name","rate"]]

                                                    name    rate
0                                                  Jalsa   4.1/5
1                                         Spice Elephant   4.1/5
2                                        San Churro Cafe   3.8/5
3                                  Addhuri Udupi Bhojana   3.7/5
4                                          Grand Village   3.8/5
...                                                  ...     ...
23188                                 Izakaya Gastro Pub  3.8 /5
23189        M Bar - Bengaluru Marriott Hotel Whitefield  3.9 /5
23190                             Keys Cafe - Keys Hotel  2.8 /5
23191                                            Bhagini  2.5 /5
23192  Chime - Sheraton Grand Bengaluru Whitefield Ho...  4.3 /5

[23193 rows x 2 columns]

In [38]:
df.rename(columns = {'rate':'ratings'},inplace=True)

In [40]:
df.head()

,url,address,name,online_order,book_table,ratings,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [41]:
df['ratings']= df['ratings'].replace('NEW','4.0/5')

In [42]:
df['ratings'].unique()

array(['4.1/5', '3.8/5', '3.7/5', '4.6/5', '4.0/5', '4.2/5', '3.9/5',
       '3.0/5', '3.6/5', '2.8/5', '4.4/5', '3.1/5', '4.3/5', '2.6/5',
       '3.3/5', '3.5/5', '3.8 /5', '3.2/5', '4.5/5', '2.5/5', '2.9/5',
       '3.4/5', '2.7/5', '4.7/5', '2.4/5', '2.2/5', '2.3/5', '4.8/5',
       '3.9 /5', '4.2 /5', '4.0 /5', '4.1 /5', '2.9 /5', '2.7 /5',
       '2.5 /5', '2.6 /5', '4.5 /5', '4.3 /5', '3.7 /5', '4.4 /5',
       '4.9/5', '2.1/5', '2.0/5', '1.8/5', '3.4 /5', '3.6 /5', '3.3 /5',
       '4.6 /5', '4.9 /5', '3.2 /5', '3.0 /5', '2.8 /5', '3.5 /5',
       '3.1 /5', '4.8 /5', '2.3 /5', '4.7 /5', '2.4 /5', '2.1 /5',
       '2.2 /5', '2.0 /5', '1.8 /5'], dtype=object)

In [43]:
df['ratings']= df['ratings'].str[:3].astype(float)

In [44]:
df.describe()

            ratings         votes
count  23193.000000  23193.000000
mean       3.904989    601.074462
std        0.425079   1114.854301
min        1.800000      0.000000
25%        3.800000    101.000000
50%        4.000000    221.000000
75%        4.200000    586.000000
max        4.900000  16832.000000

In [45]:
df.to_csv('cleaned_data.csv')

In [46]:
df.iloc[0:2,0:2]

,url,address
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."

In [47]:
df.iloc[-2:-1]

,url,address,name,online_order,book_table,ratings,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield

In [48]:
df['flag'] = 1

In [49]:
df_explicit = df.set_index("name")

df_explicit.loc[["Jalsa", "Grand Village"], ["flag"]]

               flag
name
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Grand Village     1
Grand Village     1
Grand Village     1
Grand Village     1

In [50]:
df_explicit.loc["Jalsa","flag"]=0

In [51]:
df_explicit

,url,address,online_order,book_table,ratings,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),flag
name,,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,0
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,1
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,1
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,1
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,1
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,1
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,1
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,1
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,1

In [52]:
df_explicit.loc[df_explicit["votes"]>500, "flag"] = -1

In [53]:
df_explicit

,url,address,online_order,book_table,ratings,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city),flag
name,,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,-1
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,-1
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,-1
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,1
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",'1200.0',"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,1
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,'2000.0',"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,1
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",'1200.0',"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,1
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",'800.0',"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,1
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,'2500.0',"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,1

In [54]:
data1 = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}


data2 = {
    "Restaurant": ["R5", "R6"],
    "Votes": [90, 110],
    "Rating": [3.8, 4.3]
}


df1= pd.DataFrame(data1)
df2= pd.DataFrame(data2)

In [55]:
df1

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R4     80     4.0

In [56]:
df2

  Restaurant  Votes  Rating
0         R5     90     3.8
1         R6    110     4.3

In [62]:
final_df = pd.concat([df1,df2],axis=0)

final_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R4     80     4.0
0         R5     90     3.8
1         R6    110     4.3

In [64]:
final_df = pd.concat([df1,df2], axis=0).reset_index(drop=True)

final_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R4     80     4.0
4         R5     90     3.8
5         R6    110     4.3

In [65]:
new_columns = {
    "Delivery Time (mins)": [30, 25, 35, 20, 40, 28]
}

new_df= pd.DataFrame(new_columns)

In [66]:
new_df

   Delivery Time (mins)
0                    30
1                    25
2                    35
3                    20
4                    40
5                    28

In [67]:
pd.concat([final_df,new_df],axis=1)

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.1                    30
1         R2    240     4.5                    25
2         R3    150     3.9                    35
3         R4     80     4.0                    20
4         R5     90     3.8                    40
5         R6    110     4.3                    28

In [68]:
##########
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}

sample_df = pd.DataFrame(data)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [69]:
# Can I take tontal number of votes directly?

#Data wrangling or preparing your data for modeling.

################# To identify ####################

sample_df.duplicated(keep='first')

#sample_df.duplicated(keep='last')

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [70]:
sample_df.drop_duplicates(keep='first',inplace=True)

sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [71]:
sample_df.loc[sample_df["Votes"]>=150, "Rating"] = 4.2

In [72]:
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.2
2         R3    150     4.2
4         R4     80     4.0

In [73]:
sample_df.drop_duplicates(subset=['Rating'], keep='first', inplace=True)

In [74]:
sample_df.sort_values(by=["Votes","Rating"], ascending=[True, False])

  Restaurant  Votes  Rating
4         R4     80     4.0
0         R1    120     4.1
1         R2    240     4.2

In [75]:
sample_df.sort_values(by=["Votes"], ascending=[True])

  Restaurant  Votes  Rating
4         R4     80     4.0
0         R1    120     4.1
1         R2    240     4.2